// This list is from our '01_generate_data.py' script
export const LOCATIONS_IN_DELHI = [
  "Indira Gandhi International Airport (T3)",
  "New Delhi Railway Station",
  "Connaught Place",
  "India Gate",
  "Red Fort",
  "Qutub Minar",
  "Hauz Khas Village",
  "Chandni Chowk",
  "Saket (Select Citywalk Mall)",
  "Vasant Kunj (DLF Emporio)",
  "Karol Bagh Market",
  "Lajpat Nagar Central Market",
  "Nehru Place",
  "IIT Delhi",
  "Delhi University (North Campus)",
  "AIIMS",
  "Gurgaon (Cyber Hub)",
  "Noida (Sector 18)",
  "Akshardham Temple",
  "Lotus Temple",
  "JNU",
  "Dwarka (Sector 21 Metro)",
  "Anand Vihar ISBT",
  "Kashmere Gate ISBT",
  "Sarojini Nagar Market",
  "Khan Market",
  "Humayun's Tomb",
  "Lodhi Garden",
  "Rajiv Chowk Metro",
  "Mandi House",
  "Pragati Maidan",
  "Chanakyapuri (Diplomatic Enclave)",
  "Paharganj",
  "Mayur Vihar Phase 1",
  "Rohini (Sector 18)",
  "Pitampura (TV Tower)",
  "Janakpuri (District Centre)",
  "Uttam Nagar",
  "Greater Kailash (M-Block Market)",
  "South Extension",
  "INA Market",
  "CR Park",
  "Malviya Nagar",
  "Okhla Industrial Area",
  "Patel Nagar",
  "Laxmi Nagar",
  "Civil Lines",
  "Model Town",
  "Shahdara",
  "Mehrauli",
  "Ghaziabad (Kaushambi Metro)"
];

